### ISSUE TITLE
Not working after install

### ISSUE THREAD

**Issue by trashie65** [alexopus/ComfyUI-Image-Saver#12]
Hi ive installed your custom node via Manager loaded your workflow, and all i get is the following error when trying to use it:

![error save](https://github.com/alexopus/ComfyUI-Image-Saver/assets/45748708/549c60ec-21d0-42ed-9575-409fc9b639d2)

**Comment by alexopus** [comment]
I tried it on a fresh Comfy install and I see no issues.

It must be something in your environment. Try to:
1. load default workflow.
2. remove the node set,
3. restart comfy and refresh the comfy tab.
4. install the node set.
5. restart comfy and refresh the comfy tab.
6. drop in the example workflow.

If it doesn't help, check if console log for conflicts or any additional hints.

**Comment by trashie65** [comment]
Ok thanks... did a clean Comfy & venv install all ok now....
