### ISSUE TITLE
"save image w meta data" node  does not connect with "Checkpoint Load with Namer"

### ISSUE THREAD

**Issue by MokkaBoss1** [alexopus/ComfyUI-Image-Saver#13]
![image](https://github.com/alexopus/ComfyUI-Image-Saver/assets/136205220/af46d117-4c23-47f2-8137-849f736ae2fe)

I have difficulty connecting these 2 nodes from your node suite. It seems they should like each other.

Any ideas?

thanks

MokkaBoss1

**Comment by alexopus** [comment]
Connect like this:
![image](https://github.com/alexopus/ComfyUI-Image-Saver/assets/25933468/88c1db07-9c72-4d75-a64f-05173d10581c)

**Comment by alexopus** [comment]
Closing, I don't see a problem. Reopen/comment if you disagree.

**Comment by MokkaBoss1** [comment]
the checkpoint loader with name node now has now been removed I think from your nodes.py

![image](https://github.com/alexopus/ComfyUI-Image-Saver/assets/136205220/46b5eea7-e42c-4c4c-86bb-d3edb386fe3b)


I switched to the simpler "Checkpoint Selector" which words so I'm happy to leave the case closed. Thankyou.
