### ISSUE TITLE
Is possible do not leak my workflow?

### ISSUE THREAD

**Issue by lverangel** [alexopus/ComfyUI-Image-Saver#18]
I think if i checked save workflow as json then it will not leak my worklow.

**Comment by alexopus** [comment]
Can you explain what you mean with "leak"?

**Comment by lverangel** [comment]
I sumbit my image on civitai, and a guy right click and save the picture
,then drag it into comfyUI, it will import my workflow. there are so many
personal training notice in it.
but at last, i found if save format as jpeg with the node, the
image(workflow) can not be import.
there is another custom node do this well,(civitai can read the
prompt,checkpoints,etc... and do not 'leak' ) but it nolonger update, so i
think this one can do it also.
but i save as jpeg now,so, i think it not a problem

Alexopus ***@***.***> 于2024年5月11日周六 02:29写道：

**Comment by alexopus** [comment]
Right, I see. It is unfortunate that you've leaked your personal notes like that. But saving the workflow with PNG is the default behavior of Comfy, so I kept it here too and it is documented in the first paragraph in the readme:
> For PNG stores both the full workflow in comfy format, plus a1111-style parameters. For JPEG/WEBP only the a1111-style parameters are stored.

That said, I can make it an option (default=ON) *not* to save the workflow for PNG.

**Comment by lverangel** [comment]
oh , that's my fault, i think it because i was used another plugin
before, and there is a toggle "save workflow as json"....so i thought it
will remove the workflow in PNG when i turn it on...
but I would like submit PNG on civitai,and save low quality JPG as snapshot
to save workflow.I'm not sure,maybe make an option is a good idea.
great work,and sorry for my english.


Alexopus ***@***.***> 于2024年5月11日周六 05:42写道：
