### ISSUE TITLE
Unable to get lora data to embed in a way Civitai can read - can you please an an example workflow

### ISSUE THREAD

**Issue by DrStalker** [alexopus/ComfyUI-Image-Saver#29]
I've gotten everything to work so Civitai reads it on upload except for the lora data, and I'm not sure what I'm doing wrong.

Could you please add an example workflow that embed lora info?

(Also, great nodes - thanks for making this, I hated uploading to Civitai without sharing useful generation data)

**Comment by alexopus** [comment]
to use ImpactWildcardEncode from the [ComfyUI-Impact-Pack](https://github.com/ltdrdata/ComfyUI-Impact-Pack).

In my readme there is an example in the second picture. It's a png that you can drag and drop into comfy to get the example workflow.

**Comment by alexopus** [comment]
Here it is again:

![workflow](https://github.com/alexopus/ComfyUI-Image-Saver/assets/25933468/69bf57b4-b82e-481d-a888-e0dba3867ae9)
