### ISSUE TITLE
Widget Behavior for Steps that are Multiples of 8

### ISSUE THREAD

**Issue by fernicar** [alexopus/ComfyUI-Image-Saver#32]
https://github.com/alexopus/ComfyUI-Image-Saver/blob/d30a782d9fa90f64c7de631fcb6d19017a6d5e63/nodes.py#L99
https://github.com/alexopus/ComfyUI-Image-Saver/blob/d30a782d9fa90f64c7de631fcb6d19017a6d5e63/nodes.py#L309
https://github.com/alexopus/ComfyUI-Image-Saver/blob/d30a782d9fa90f64c7de631fcb6d19017a6d5e63/nodes.py#L310

**Widget Behavior for Steps that are Multiples of 8:**
When the minimum value is set to 1, each step will not behave as expected and will always result in an odd number. Please consider setting the minimum value to 0 or 8. Thank you.

**Comment by alexopus** [comment]
Thank you! Fixed in main.
