### ISSUE TITLE
[Bug] sampler_name turned into error

### ISSUE THREAD

**Issue by AlUlkesh** [alexopus/ComfyUI-Image-Saver#36]
I just updated to the latest commit and now all my Image Saver nodes have this red error mark on "sampler_name":

![image](https://github.com/user-attachments/assets/2fcbac4a-9299-4ee0-ab62-a01e8e18e634)

Any idea what might have happened?

**Comment by alexopus** [comment]
Most likely you need to connect the string output (second one from the sampler selector) instead of the typed one (first). Also, recreate the sampler selector node to get the correct name. 
If it doesn't help, try recreating the saver node.

**Comment by AlUlkesh** [comment]
Thanks. I got it working by converting sampler_name to widget and back again.
