### ISSUE TITLE
Basemodelname not saving

### ISSUE THREAD

**Issue by ardri1166** [alexopus/ComfyUI-Image-Saver#37]
Timestamp is applied correctly, but the checkpoint name is missing.

![image](https://github.com/user-attachments/assets/a772480f-adde-4da6-947c-863ab3d0f6fc)
![image](https://github.com/user-attachments/assets/b303d7ca-cee4-4cce-b82a-c6c3f188155b)
![image](https://github.com/user-attachments/assets/0134afbb-3e3a-412a-9be3-00ca33afd5f4)

**Comment by alexopus** [comment]
Works fine for me. 
Wanna share your workflow json?

**Comment by ardri1166** [comment]
Never mind, I'm just stupid lol. I'm used to the other Metadata saver where everything is pulled in without having to spaghetti everything together manually. Unfortunately that one throws an error every week now so I need to go back to this one and rearrange all my workflows to include the manual feeding of the meta data.

![image](https://github.com/user-attachments/assets/0ea057bb-ee46-4281-967d-b87c0f5b8d91)

**Comment by alexopus** [comment]
np!
