### ISSUE TITLE
TypeError: ImageSaver.save_files() missing 1 required positional argument: 'clip_skip'

### ISSUE THREAD

**Issue by BrechtCorbeel** [alexopus/ComfyUI-Image-Saver#47]
`Start update check...Processing image with shape:  992 x 1496 to  1984 x 2992
!!! Exception during processing !!! ImageSaver.save_files() missing 1 required positional argument: 'clip_skip'
Traceback (most recent call last):
  File "W:\smatrix\Data\Packages\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "W:\smatrix\Data\Packages\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "W:\smatrix\Data\Packages\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "W:\smatrix\Data\Packages\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
TypeError: ImageSaver.save_files() missing 1 required positional argument: 'clip_skip'`

Error message below, I think this might be an update issue? I just updated, does this mean some node needs updating too and has a mismatch? this workflow worked fine until now.

**Comment by BrechtCorbeel** [comment]
Looking at the code from the repo here, this was added 4 days ago and causing issues.

**Comment by BrechtCorbeel** [comment]
Sorry accidentally closed.

**Comment by BrechtCorbeel** [comment]
I am currently trying a previous version of the nodes.py.

I do want to mention, I am batching an array of 100s +- 2000 workflows that are built on previous version.

This issue is likely caused by a now mismatch between these workflows and the new version needing this parameter. Since they do not have it, it is causing this issue. 

Since this is not required to run adding an ability to skip this parameter if not given would be great.

**Comment by BrechtCorbeel** [comment]
Removing Clip_skip got it to work again.

When I create a new batch with the new version this will be fine, but I have approximately 5-10 days of generation time with this workflow ahead of me for now.

**Comment by alexopus** [comment]
New clip_skip parameter was added. You have to recreate the node either manually or with the `Fix node (recreate)` from the context menu. Or rollback to 5a90b10ba94e394bd5f307b0e74b5ee1095154c1 if you want to keep the old.
