### ISSUE TITLE
Scheduler not saved into metadata

### ISSUE THREAD

**Issue by PrometheusDante** [alexopus/ComfyUI-Image-Saver#48]
Hey there, 
the scheduler is not saved into the metadata as far as I can see, checking with exiftool as well as on CivitAI upload.

![exiftool_metadata](https://github.com/user-attachments/assets/2c12a5c9-9c57-4768-ba2b-474f113ed28c)

Test image + workflow in .zip as Github does not pick up on .webp files
[metadata_scheduler_test.zip](https://github.com/user-attachments/files/17604170/metadata_scheduler_test.zip)

The recent update that introduced clip-skip saving does also neither appear in exiftool's metadata nor on CivitAI.

**Comment by alexopus** [comment]
Civitai doesn't support a full sampler + scheduler combo, but rather a short list of combinations: https://github.com/civitai/civitai/blob/main/src/server/common/constants.ts#L139-L165
So this node only attempts to pick one of those valid combinations, while others are ignored:
https://github.com/alexopus/ComfyUI-Image-Saver/blob/main/nodes.py#L333-L369

As for clip skip, that is filled only if it is non-zero.

**Comment by PrometheusDante** [comment]
I see, what a weird system for them to use then.

Can confirm the clip-skip does get picked up on when non-zero 👍

Thanks for the quick answer and continuous support!

**Comment by alexopus** [comment]
It is historical. In the past a1111 supported only those combinations. Hopefully this will be updated in the future.
