### ISSUE TITLE
Can we have a loader, or a bridge that extract the name of the model to string?

### ISSUE THREAD

**Issue by LiJT** [alexopus/ComfyUI-Image-Saver#49]
![PixPin_2024-11-15_01-04-27](https://github.com/user-attachments/assets/945d0950-0234-48bf-9d23-bbdd9eadd90b)

Like this? Or simple a universal string transfer tool, transfer the name of model to string, then we can feed that information to the Image Saver node. so we can upload our image to civitai the model information will be there? 

I tired this method, still not working. The output image reject my custom prefix!
![PixPin_2024-11-15_02-32-08](https://github.com/user-attachments/assets/a121d9e7-282e-40d7-9715-3f0085c80687)

Very like you make this ancient node back to alive! Thank you for maintaining this!

**Comment by alexopus** [comment]
Adding extra nodes just for extracting names as strings is not a solution that scales well.
If a more general approach is offered by KJNodes then please just use that. It seems to be a well maintained node set.
ComfyUI moves fast and there are breaking changes, which is not a bad thing by itself. Duplicating the functionality will only make it break in two places on the next update ;).
Ideally such a functionality should be offered by ComfyUI (frontend) itself - use any node widget values as strings in other strings.

**Comment by alexopus** [comment]
I added a UNetLoaderWithName node.
![image](https://github.com/user-attachments/assets/f77edc67-c537-4e2f-bb06-f159e26b9419)
![image](https://github.com/user-attachments/assets/f529cfc1-8520-4707-8a2f-dffe62b097f1)

**Comment by Tinase-nau** [comment]
Welcome to the world of Flux @alexopus I also see you got the good model for start. You'll be sticking with it for a long time. :P

Btw, in case of Flux, the Image Saver node doesn't require the Negative field as Flux gets all the info from a single blob of text.
It's just a gross field taking up space on the node. Currently using a primitive to just pass nothing to it to hide the field.

Also, what is that snake (🐍) node from? I see everyone using it, but Idk what do I have to install. I see it has value and I know it may come in handy.

**Comment by alexopus** [comment]
It's from here: https://github.com/pythongosssss/ComfyUI-Custom-Scripts/
