### ISSUE TITLE
Can't connect "Scheduler Selector (Image Saver)" to BasicScheduler

### ISSUE THREAD

**Issue by alex-mitov** [alexopus/ComfyUI-Image-Saver#50]
I can't connect the the "scheduler" output of the "Scheduler Selector (Image Saver)" node to the "scheduler" input of the "BasicScheduler" after I convert its scheduler widget to input. Am I using this wrong? Please check the screenshot below.

![scheduler-selector-wont-connect](https://github.com/user-attachments/assets/2ec12342-facb-4e16-b59d-85b07ac99ba5)

**Comment by alex-mitov** [comment]
Ok, I found a workaround until this is fixed. You can use the "Widget to String" node from KJNodes to achieve this.

1. Make sure you have KJNodes. If not, install them first from the Manager. They are called "KJNodes for ComfyUI".
2. Create a "Widget to String" node and connect the "scheduler" output of the "Scheduler Selector (Image Saver)" node to the "any_input" input of the "Widget to String" node.
3. Where it says "widget_name" write the name of the widget that you want to turn into string. In our case this is the "scheduler" widget so we write "scheduler" there.
4. Connect the "STRING" output of the "Widget to String" node to the scheduler input of the "Image Saver" node. If you don't see this input, you must first convert the widget to input by right clicking on the "Image Saver" node, clicking on "Convert Widget to Input" from the list and then clicking on "Convert scheduler to input". Now you can connect it there.

I hope this helps!

**Comment by alexopus** [comment]
Try to use the `Scheduler Selector (Comfy) (Image Saver)` node.

**Comment by alex-mitov** [comment]
That worked! Thanks!
